language: node_js
node_js:
  - "stable"
install:
  - npm ci
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER native WITH PASSWORD 'designs';" -U postgres
  - npm run build
  - npm install -g sequelize -cli
  - npm run db-migrate
script:
  - npm test
after_success:
  - npm run coverage
env:
  global:
    -CODECLIMATE_REPO_TOKEN=1fdbd27f1c37fceea08d760e3e7e9c3519ce6aff574f77b3605cd9cd36faa3c9